// Generated by scripts/gen-reserved-words.mjs from TypeScript 5.9.3.
// Do not edit; is-reserved.test.ts fails when this table drifts from the installed TypeScript.

/**
 * TypeScript's ReservedWord range: never an identifier.
 */
export const RESERVED_WORDS: readonly string[] = [
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
]

/**
 * TypeScript's FutureReservedWord range: reserved in strict mode code.
 */
export const STRICT_MODE_RESERVED_WORDS: readonly string[] = [
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield',
]

/**
 * TypeScript's ContextualKeyword range: keywords that remain legal identifiers.
 */
export const CONTEXTUAL_KEYWORDS: readonly string[] = [
  'abstract',
  'accessor',
  'any',
  'as',
  'assert',
  'asserts',
  'async',
  'await',
  'bigint',
  'boolean',
  'constructor',
  'declare',
  'defer',
  'from',
  'get',
  'global',
  'infer',
  'intrinsic',
  'is',
  'keyof',
  'module',
  'namespace',
  'never',
  'number',
  'object',
  'of',
  'out',
  'override',
  'readonly',
  'require',
  'satisfies',
  'set',
  'string',
  'symbol',
  'type',
  'undefined',
  'unique',
  'unknown',
  'using',
]
