/**
 * TypeScript's ContextualKeyword range: keywords that remain legal identifiers.
 *
 * Generated by scripts/gen-reserved-words.mjs from TypeScript 5.9.3; not edited
 * by hand. reserved.test.ts fails when this table drifts from the installed
 * TypeScript.
 */
export const CONTEXTUAL_KEYWORDS: ReadonlySet<string> = new Set([
  'abstract',
  'accessor',
  'any',
  'as',
  'assert',
  'asserts',
  'async',
  'await',
  'bigint',
  'boolean',
  'constructor',
  'declare',
  'defer',
  'from',
  'get',
  'global',
  'infer',
  'intrinsic',
  'is',
  'keyof',
  'module',
  'namespace',
  'never',
  'number',
  'object',
  'of',
  'out',
  'override',
  'readonly',
  'require',
  'satisfies',
  'set',
  'string',
  'symbol',
  'type',
  'undefined',
  'unique',
  'unknown',
  'using',
])
