/**
 * TypeScript's ReservedWord range: never an identifier.
 *
 * Generated by scripts/gen-reserved-words.mjs from TypeScript 5.9.3; not edited
 * by hand. reserved.test.ts fails when this table drifts from the installed
 * TypeScript.
 */
export const RESERVED_WORDS: ReadonlySet<string> = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
])
