/**
 * TypeScript's FutureReservedWord range: reserved in strict mode code.
 *
 * Generated by scripts/gen-reserved-words.mjs from TypeScript 5.9.3; not edited
 * by hand. reserved.test.ts fails when this table drifts from the installed
 * TypeScript.
 */
export const STRICT_MODE_RESERVED_WORDS: ReadonlySet<string> = new Set([
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield',
])
